name := "scala-spark-etl-validator"
version := "0.1"
scalaVersion := "2.11.12"
libraryDependencies += "com.github.etaty" %% "rediscala" % "1.9.0"
libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.5.26"
libraryDependencies += "com.amazonaws.services.glue" % "aws-glue" % "2.2.1" from "https://aws-glue-jes-prod-sa-east-1-assets.s3.amazonaws.com/etl-2.2.1/jars/glue-assembly.jar"
libraryDependencies += "com.amazonaws" % "aws-java-sdk" % "1.11.623"
libraryDependencies += "org.apache.httpcomponents" % "httpclient" % "4.5.9"
libraryDependencies += "org.apache.hadoop" % "hadoop-aws" % "2.8.5"
libraryDependencies += "org.apache.hadoop" % "hadoop-common" % "2.8.0"
libraryDependencies += "org.apache.spark" % "spark-core_2.11" % "2.4.3"
libraryDependencies += "org.apache.spark" % "spark-mllib_2.11" % "2.2.1"
libraryDependencies += "org.apache.spark" % "spark-repl_2.11" % "2.2.1"
libraryDependencies += "org.apache.spark" % "spark-sql_2.11" % "2.4.3"
libraryDependencies += "org.apache.spark" % "spark-network-shuffle_2.11" % "2.2.1"
libraryDependencies += "org.apache.spark" % "spark-hive_2.11" % "2.4.3"
libraryDependencies += "org.apache.spark" % "spark-mesos_2.11" % "2.2.1"
libraryDependencies += "org.apache.spark" % "spark-graphx_2.11" % "2.2.1"
libraryDependencies += "org.apache.spark" % "spark-catalyst_2.11" % "2.2.1"
libraryDependencies += "org.apache.spark" % "spark-launcher_2.11" % "2.2.1"

libraryDependencies += "com.amazon.redshift" % "redshift-jdbc42" % "1.2.37.1061" from "https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.37.1061/RedshiftJDBC42-no-awssdk-1.2.37.1061.jar"

libraryDependencies += "com.microsoft.sqlserver" % "mssql-jdbc" % "6.1.0.jre8"
