profile=$1

echo $profile
echo "Criando a política de leitura do Systems Managem - Parameter Store"

aws iam create-policy --policy-name SSMGetParameterAccess --policy-document '{"Version":"2012-10-17","Statement":[{"Sid":"VisualEditor0","Effect":"Allow","Action":["ssm:DescribeParameters","ssm:GetParameters","ssm:GetParameter"],"Resource":"*"}]}' --profile $profile

echo "Anexando a política criada a role Brasilseg-GlueRole"

aws iam attach-role-policy --policy-arn arn:aws:iam::909530209831:policy/SSMGetParameterAccess --role-name Brasilseg-Glue-Role --profile $profile

echo "Apontando para o diretório de scripts ..."

cd script

echo "Assistência BB3.0"

./glue.sh job-update-parameters --job-name carga_assistencia_redis_ab_mobile_assistencia_db --parameters "{'Command':{'ScriptLocation':'s3://datalake-glue-scripts/carga_historica/carga_redis/assistencia_db_carga_redis_unificada.scala'},'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar,s3://datalake-glue-scripts/dependencias_scala/Assistencia_AB/entityDependencies.jar','--extra-files':'s3://datalake-glue-scripts/estrutura_tabela/estrutura_assistencia_ab_mobile.json,s3://datalake-glue-scripts/estrutura_query/AssistenciaABQuerys.json','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--environment':'aws','--database':'ab','--redshift_schema':'spectrum_assistencia_db_ab_mobile','--schema':'estrutura_assistencia_ab_mobile.json','--queries':'AssistenciaABQuerys.json','--enable-spark-ui':'true','--conf':'spark.driver.maxResultSize=10g','--spark-event-logs-path':'s3://brasilseg-glue-log/carga_assistencia_redis_ab_mobile_assistencia_db/','--enable-s3-parquet-optimized-committer':'true'},'GlueVersion':'2.0'}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name carga_assistencia_redis_ab_mobile_assistencia_db_incremental --parameters "{'Command':{'ScriptLocation':'s3://datalake-glue-scripts/carga_historica/carga_redis/assistencia_db_carga_redis_unificada.scala'},'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar,s3://datalake-glue-scripts/dependencias_scala/Assistencia_AB/entityDependencies.jar','--extra-files':'s3://datalake-glue-scripts/estrutura_tabela/estrutura_assistencia_ab_mobile.json,s3://datalake-glue-scripts/estrutura_query/AssistenciaABQuerys.json','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--environment':'aws','--database':'ab','--redshift_schema':'spectrum_assistencia_db_ab_mobile','--schema':'estrutura_assistencia_ab_mobile.json','--queries':'AssistenciaABQuerys.json','--enable-spark-ui':'true','--conf':'spark.driver.maxResultSize=10g','--spark-event-logs-path':'s3://brasilseg-glue-log/carga_assistencia_redis_ab_mobile_assistencia_db_incremental/','--enable-s3-parquet-optimized-committer':'true'},'GlueVersion':'2.0'}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name carga_assistencia_redis_abs_mobile_assistencia_db --parameters "{'Command':{'ScriptLocation':'s3://datalake-glue-scripts/carga_historica/carga_redis/assistencia_db_carga_redis_unificada.scala'},'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar,s3://datalake-glue-scripts/dependencias_scala/Assistencia_ABS/entityDependencies.jar','--extra-files':'s3//datalake-glue-scripts/estrutura_tabela/estrutura_assistencia_abs_mobile.json,s3://datalake-glue-scripts/estrutura_query/AssistenciaABSQuerys.json','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--environment':'aws','--database':'abs','--redshift_schema':'spectrum_assistencia_db_abs_mobile','--schema':'estrutura_assistencia_abs_mobile.json','--queries':'AssistenciaABSQuerys.json','--enable-spark-ui':'true','--conf':'spark.driver.maxResultSize=10g','--spark-event-logs-path':'s3://brasilseg-glue-log/carga_assistencia_redis_abs_mobile_assistencia_db/','--enable-s3-parquet-optimized-committer':'true'},'GlueVersion':'2.0'}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name carga_assistencia_redis_abs_mobile_assistencia_db_incremental --parameters "{'Command':{'ScriptLocation':'s3://datalake-glue-scripts/carga_historica/carga_redis/assistencia_db_carga_redis_unificada.scala'},'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar,s3://datalake-glue-scripts/dependencias_scala/Assistencia_ABS/entityDependencies.jar','--extra-files':'s3//datalake-glue-scripts/estrutura_tabela/estrutura_assistencia_abs_mobile.json,s3://datalake-glue-scripts/estrutura_query/AssistenciaABSQuerys.json','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--environment':'aws','--database':'abs','--redshift_schema':'spectrum_assistencia_db_abs_mobile','--schema':'estrutura_assistencia_abs_mobile.json','--queries':'AssistenciaABSQuerys.json','--enable-spark-ui':'true','--conf':'spark.driver.maxResultSize=10g','--spark-event-logs-path':'s3://brasilseg-glue-log/carga_assistencia_redis_abs_mobile_assistencia_db_incremental/','--enable-s3-parquet-optimized-committer':'true'},'GlueVersion':'2.0'}" --region us-east-1 --profile $profile

echo "Proposta BB3.0"

./glue.sh job-update-parameters --job-name bb30_carga_proposta_redis_home --parameters "{'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_ssl':'true','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_auth':'/brseg/elasticache/brasilseg-redis/token'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name bb30_carga_proposta_redis_prestamista_historico --parameters "{'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_ssl':'true','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_auth':'/brseg/elasticache/brasilseg-redis/token'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name bb30_carga_proposta_redis_prestamista_incremental --parameters "{'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_ssl':'true','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_auth':'/brseg/elasticache/brasilseg-redis/token'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name bb30_carga_proposta_redis_residencial_historico --parameters "{'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_ssl':'true','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_auth':'/brseg/elasticache/brasilseg-redis/token'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name bb30_carga_proposta_redis_residencial_incremental --parameters "{'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_ssl':'true','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--conf':'spark.driver.maxResultSize=10g'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name bb30_carga_proposta_redis_rural_ab_historico --parameters "{'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_ssl':'true','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--enable-s3-parquet-optimized-committer':'true'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name bb30_carga_proposta_redis_rural_ab_incremental --parameters "{'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_ssl':'true','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_auth':'/brseg/elasticache/brasilseg-redis/token'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name bb30_carga_proposta_redis_rural_abs_historico --parameters "{'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_ssl':'true','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_auth':'/brseg/elasticache/brasilseg-redis/token'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name bb30_carga_proposta_redis_rural_abs_incremental --parameters "{'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_ssl':'true','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_auth':'/brseg/elasticache/brasilseg-redis/token'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name bb30_carga_proposta_redis_vida_historico --parameters "{'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_ssl':'true','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_auth':'/brseg/elasticache/brasilseg-redis/token'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name bb30_carga_proposta_redis_vida_incremental --parameters "{'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_ssl':'true','--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--conf':'spark.driver.maxResultSize=10g'}}" --region us-east-1 --profile $profile

echo "Evento Sinistro BB3.0"

./glue.sh job-update-parameters --job-name carga_evento_sinistro_redis_ab_mobile_seguros_db --parameters "{'DefaultArguments':{'--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--environment':'aws','--database':'ab','--conf':'spark.driver.memory=10g','--enable-s3-parquet-optimized-committer':'true','--enable-spark-ui':'true'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name carga_evento_sinistro_redis_ab_mobile_seguros_db_incremental --parameters "{'DefaultArguments':{'--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--environment':'aws','--database':'ab','--enable-s3-parquet-optimized-committer':'true','--enable-spark-ui':'true'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name carga_evento_sinistro_redis_abs_mobile_seguros_db --parameters "{'DefaultArguments':{'--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--environment':'aws','--database':'abs','--enable-s3-parquet-optimized-committer':'true','--enable-spark-ui':'true'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name carga_evento_sinistro_redis_abs_mobile_seguros_db_incremental --parameters "{'DefaultArguments':{'--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--environment':'aws','--database':'abs','--enable-s3-parquet-optimized-committer':'true','--enable-spark-ui':'true'}}" --region us-east-1 --profile $profile

echo "Sinistro BB3.0"

aws glue create-job --name bb30_carga_sinistro_redis_ab_historico --role arn:aws:iam::909530209831:role/Brasilseg-Glue-Role --execution-property MaxConcurrentRuns=1 --command Name=glueetl,ScriptLocation=s3://datalake-glue-scripts/carga_historica/carga_redis/carga_sinistro_redis_ab_seguros_db.py,PythonVersion=3 --connections Connections=dw_db --max-retries 0 --allocated-capacity 11 --glue-version 2.0 --default-arguments '{"--TempDir": "s3://aws-glue-temporary-909530209831-us-east-1/admin","--conf": "spark.driver.memory=10g","--enable-continuous-cloudwatch-log": "true","--enable-metrics": "","--enable-s3-parquet-optimized-committer": "true","--enable-spark-ui": "true","--environment": "aws","--extra-py-files": "s3://datalake-glue-scripts/dependencias_python/redis.zip","--job-bookmark-option": "job-bookmark-disable","--job-language": "python","--redis_auth": "/brseg/elasticache/brasilseg-redis/token","--redis_db": "3","--redis_host": "/brseg/elasticache/brasilseg-redis/endpoint","--redis_port": "/brseg/elasticache/brasilseg-redis/porta","--redis_ssl": "true","--redshift_credentials": "prd/redshiftDW","--redshift_key_path": "null","--database": "ultron","--spark-event-logs-path": "s3://brasilseg-glue-log/bb30_carga_sinistro_redis_ab_historico/","--type": "full"}' --region us-east-1 --profile $profile
aws glue create-job --name bb30_carga_sinistro_redis_ab_incremental --role arn:aws:iam::909530209831:role/Brasilseg-Glue-Role --execution-property MaxConcurrentRuns=1 --command Name=glueetl,ScriptLocation=s3://datalake-glue-scripts/carga_historica/carga_redis/carga_sinistro_redis_ab_seguros_db.py,PythonVersion=3 --connections Connections=dw_db --max-retries 0 --allocated-capacity 11 --glue-version 2.0 --default-arguments '{"--TempDir": "s3://aws-glue-temporary-909530209831-us-east-1/admin","--conf": "spark.driver.memory=10g","--enable-continuous-cloudwatch-log": "true","--enable-metrics": "","--enable-s3-parquet-optimized-committer": "true","--enable-spark-ui": "true","--environment": "aws","--extra-py-files": "s3://datalake-glue-scripts/dependencias_python/redis.zip","--job-bookmark-option": "job-bookmark-disable","--job-language": "python","--redis_auth": "/brseg/elasticache/brasilseg-redis/token","--redis_db": "3","--redis_host": "/brseg/elasticache/brasilseg-redis/endpoint","--redis_port": "/brseg/elasticache/brasilseg-redis/porta","--redis_ssl": "true","--redshift_credentials": "prd/redshiftDW","--redshift_key_path": "s3://brasilseg-segbr-extracao/chaves-redis/ab_mobile/sinistro","--database": "ultron","--spark-event-logs-path": "s3://brasilseg-glue-log/bb30_carga_sinistro_redis_ab_incremental/","--type": "increment"}' --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name carga_sinistro_redis_abs_mobile_seguros_db --parameters "{'DefaultArguments':{'--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--environment':'aws','--database':'abs','--enable-s3-parquet-optimized-committer':'true','--enable-spark-ui':'true'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name carga_sinistro_redis_abs_mobile_seguros_db_incremental --parameters "{'DefaultArguments':{'--redis_host':'/brseg/elasticache/brasilseg-redis/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis/token','--environment':'aws','--database':'abs','--enable-s3-parquet-optimized-committer':'true','--enable-spark-ui':'true'}}" --region us-east-1 --profile $profile

echo "Aviso Web"

./glue.sh job-update-parameters --job-name asw_carga_redis_ab_seguros_db_incremental_async_proposta --parameters "{'Command':{'ScriptLocation':'s3://datalake-glue-scripts/carga_historica/carga_redis/asw_carga_unificada_redis_ab_seguros_db.scala'},'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_host':'/brseg/elasticache/brasilseg-redis-aviso/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis-aviso/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis-aviso/token','--query':'proposta_ab_redshift_queries.json','--environment':'aws','--enable-s3-parquet-optimized-committer':'true','--enable-spark-ui':'true','--executor-memory':'10g'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name asw_carga_redis_ab_seguros_db_incremental_async_sinistro --parameters "{'Command':{'ScriptLocation':'s3://datalake-glue-scripts/carga_historica/carga_redis/asw_carga_unificada_redis_ab_seguros_db.scala'},'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--redis_host':'/brseg/elasticache/brasilseg-redis-aviso/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis-aviso/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis-aviso/token','--query':'sinistro_ab_redshift_queries.json','--environment':'aws','--enable-s3-parquet-optimized-committer':'true','--enable-spark-ui':'true','--executor-memory':'10g','--conf':'spark.driver.maxResultSize=10g'}}" --region us-east-1 --profile $profile
./glue.sh job-update-parameters --job-name asw_carga_redis_ab_seguros_db_historico_etl --parameters "{'Command':{'ScriptLocation':'s3://datalake-glue-scripts/carga_historica/carga_redis/asw_carga_unificada_redis_ab_seguros_db.scala'},'DefaultArguments':{'--extra-jars':'s3://datalake-glue-scripts/dependencias_scala/jedis-combined-1.0.jar','--extra-files':'s3://datalake-glue-scripts/estrutura_query/carga_historico/sinistro_ab_redshift_queries.json','--redis_host':'/brseg/elasticache/brasilseg-redis-aviso/endpoint','--redis_port':'/brseg/elasticache/brasilseg-redis-aviso/porta','--redis_ssl':'true','--redis_auth':'/brseg/elasticache/brasilseg-redis-aviso/token','--conf':'spark.yarn.executor.memory=10g','--executor-memory':'10g','--query':'sinistro_ab_redshift_queries.json'}}" --region us-east-1 --profile $profile

